# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vilya-flux
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WBZvOiYCwrU=,iv:7jBT8CltYTobyXNP9m0bIc9ZGJFjEtBb22OGF3dHyx8=,tag:qA+gksNp5SVvQ/bofxyPJA==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:nf5sIRRf6/CZYgjYJaDJ8Q==,iv:8Xrc24viukFqPAf1i3I7GBx3rEvsrhU9h11YE/1pU6Q=,tag:ClRCDoGpy9TIg6KAQNJQTw==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:LXT++fKHcV1PuK1DcDo=,iv:Os8f9DFAklTz6ee790uOt592d6JrYz+e7Kfz897qE84=,tag:QsF5BWkTV8M+3uGBoWuh/Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2rlKcLknFB4T4bEVpKOUg/kn,iv:yrZlwL1nqkcEEKhLwm/iFQd1bE2gvO3rhHRrHwmhl4c=,tag:DUnT1XNlBvopnYLBDbCROg==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:icsN1ADPTJi7umFb3/BE4zJL49sCSKEkL4XU2Z2PN8MJW7+vJw==,iv:O6C6TTGmnTVC4zwSDfeQQUsCWO/zPsgj91s09dl+vyI=,tag:asC7jtN87xSkVEWz1jANqg==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:VaSyogjuNULY7o9JSHfj6J7fN10g4AtDgq21pFs2LCKNdRcymwIA9pPUidmTFuFeJAskUXGRxg+Yo6EZgfvhD5ewSqkx5isUWOXl4Yymdy8lkzye548PoFbEsaNf/0Cxuf/rpijhyS46gAMjD2Ru1BoXwnh1GmRf,iv:H+9I7ZeH+MgSf9/gUgXFN4/FHulMZsQ84QJSAr2GeGg=,tag:y2PmTZOqD0WXXfJNyKx/Zg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:7DW5j4BhDR8HRm0AUGwt8CXb,iv:urDZKuigEpZJsWMRYxuGhiD+f5ozHnAA06WW0G4wQbg=,tag:qB6jdJUg9xr/FjHv3YO7Mg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:vZJqmgRMslU=,iv:rUCPDPcu5O3wUy5hffYDDQ18o5QKmgG5yaQcSwwXb1E=,tag:USsSr2XUJo6v2J4etVMLgA==,type:str]
    SECRET_OMADA_HOST: ENC[AES256_GCM,data:MjRq9oQOrsy7NR1ZpGlxEwsugA==,iv:WsGJ4gW6Lnbb6lHbhVxTJ8cL3fWZCmdfqgRkAcoD72U=,tag:7IfJOyQmWTlMOHpsHHf2xQ==,type:str]
    SECRET_OMADA_USERNAME: ENC[AES256_GCM,data:ENa/MsVFXUY=,iv:Ew17Wqfa2f98VH35YicOoz0YI4i6odv6K9fOXWV45no=,tag:PBkrdJQ1xN9viHJuENz7uw==,type:str]
    SECRET_OMADA_PASSWORD: ENC[AES256_GCM,data:jh1YquOmpsMEsNY0ioP2J9xzm04=,iv:MRY7zPn2IeXTieuzU5f69n+rPjCsTkyF5PtLXq/sqak=,tag:v5CQIOi+4uSLGmtrUPAY/w==,type:str]
    SECRET_CLOUDFLARED_KEY: ENC[AES256_GCM,data:yCIlm1KnWs1fZFFs3gEcvwpS7ccXNEYTTb9PiXebAvZcdxFGdQ==,iv:HfTdck/J6zzmoTP9w8oqmfIJBnb1nCj/80GH4Xe5nUI=,tag:BzmcldaOQCyHmryWmtGNBg==,type:str]
    SECRET_CLOUDFLARED_TOKEN: ENC[AES256_GCM,data:1QN3JWoM7MI2B9F2LMEADfyeC1zePjoVz2xMjZua9Hm2DNkOG8yo2Q==,iv:qZ8kK2bMuav+ZJ7+1UqixIhN39IeMJEuuIQVzmDvAsc=,tag:DqscM0ivwXGe4OIf2q33bQ==,type:str]
    SECRET_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:/51h13nUIwpKAfGYx/ySuaP+XIqjJHZiFG/96yV/A/s=,iv:164CeyUhg28yLrAL8lWRibI5cIYfHoXZdPYaQ7W36S0=,tag:1xi6IVD6+9yJ7RJCqjpSdA==,type:str]
    NETWORK_BGP_PEER: ENC[AES256_GCM,data:oqdyi42x3PmZha8=,iv:DJbKoaiyuYtSs2yW/RZvBuQA1sIw7B1J0vKbbmieeqk=,tag:Uh7uRcJomqzFJ2Sk6fXcIw==,type:str]
    NETWORK_BGP_ADDR_RANGE: ENC[AES256_GCM,data:xrdcEULj8lq+3C6Cg2U=,iv:+epdhztY0qGmC54UGhNGKrrbtS7yIcFvttXTYvmcHYY=,tag:YONMoPMmuqSEvzYlKuTh6A==,type:str]
    SECRET_EMQX_DEFAULT_PASS: ENC[AES256_GCM,data:ZeUqs2w2bhHi2e8bpYKB06h1,iv:uUdxksrtAf66o1Yk8TIaBXo7Hn00171lH3DDb+bixC4=,tag:fcKbfkUg4WpCZRkRzw31IQ==,type:str]
    SECRET_EMQX_USER: ENC[AES256_GCM,data:yLAhBw==,iv:vlwrQ2hasZRB9SkMXTdOfjRiLQ3fc3mIH4PqgM0QNkY=,tag:Eirqxp67r/A9U4gu9Y6oKA==,type:str]
    SECRET_EMQX_PASS: ENC[AES256_GCM,data:jv/iWhwEKQLlXS3eugp1QeFT,iv:rNPjS9mUoEqv13qVn1irHUJilcHkn+2GbKesDxhJeHc=,tag:s3nMeEYbgxKRwg6Aq4nD7A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:zXj8dQLuxSVKTy8LwMb7Ss2+WIJv1cc6L4X1CPliHfU9B8gd+f27EtGPH6wq5+bgsg==,iv:GmHyTNnU6MAR/sPVU4EGXbhnmygWYrtnljv6nZ1ydlk=,tag:inp38FXsFZo2INoJrt77JA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PLqjaDgMuKbBtSkQDh+qqgiNLg==,iv:+fWvILXEhpM5aGTzmkDW5hRDkJEpO8w2XM8CPetbz+U=,tag:f6A6xXETBhnjRXbABJaNgg==,type:str]
    AWS_SECRET_KEY_RESTIC: ENC[AES256_GCM,data:ex8p9TOmTFFcSwqFUw3Ywqh33E97AohWNX4v2UUcxg==,iv:yu76Kf4Ca/5bGKylRJfqF7/3EsfJH5/vRw1rHS+RMIo=,tag:Awwo8gi8bhNp/vAEzXuT3w==,type:str]
    AWS_ACCESS_KEY_RESTIC: ENC[AES256_GCM,data:F5fAWY/WxZwrVlDj6nTpxdzMzhxpOHB9Wg==,iv:phlzhFBQYACzwt913T1MZJZO2GCXUicyDN2E6gsX7uM=,tag:ujlLNJkOPMvT1JijAuP54w==,type:str]
    PULUMI_ACCESS_TOKEN: ENC[AES256_GCM,data:J7x11e/VAxLSV4hGFlP0KEECOzMNXKM/lSpg7ffOPPOA+sQ7fe4rSi39AsE=,iv:aIzrYSvR5jZOIVXQ53bTyROZmn2EEj2hSm3IdU/ivDw=,tag:m8OpM2tB4dvCcaqKjl76iA==,type:str]
    REDPANDA_PASS: ENC[AES256_GCM,data:r6zu0ZLognCaCNtOsSr4KP0+pDpOsWUHFLC9rJCZU4E=,iv:/IOyVzGa266nWBgN8AN3e/J6R49Vg6JKTlTHOYKaFoM=,tag:EnxhmLAlSxP9ZVRgGPzMXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c000ffrkz0lwqdhmkqurvj4tc2zvluhm3zh5l4ppmu5dq6y5qfls2t3vfw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdmJ3WjNDc0NSVm8zeG9h
            MFlYZThoUW1kVTFJZmt4NHArZThlaXJlbFFjCkdtMlhxT3BwZFNqeDFFNURxMnF0
            MzNyQlZkaUl1MUVRa3RYL1lxYUVEVjAKLS0tIERIeHl4WnhlamJ0cDF1a3UyRTVM
            aGtUckFqU29lYWNJdG8wRzNITS9FeTAKI1iLGvJffJNjKfKN9ADiv0YRQdQKZ8PL
            VHyNILLjI6NtlIHRcJmgWdP1fFdci1y7c//QjGXOCYQ5TbULKJgHGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-02T18:12:59Z"
    mac: ENC[AES256_GCM,data:xFr6UePPlq2O4ooYZuak3KJFOVd5MxKA8EN1lFg+tS87VAU36m5cefxQ1ii8GqORYpraq2j41uV56CgpXw3pzbd2M3D3yCjPBEvspsKEHTnq9K1I3p6nTeBYHmhi80V66ggBPzX3IMLZrJVhivTSw91X2+jq+VRzwwgzx6mee0Y=,iv:PFU8ckQPEeNNzFmkJyWGfiXHi59C5HrfL7n7T20TDWY=,tag:kWX/PEoWzSn34Bm2kjubjQ==,type:str]
    pgp:
        - created_at: "2023-12-14T19:19:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2wmGpZxIoIiAQ/+N35gm4MbCoGgeEAf0I8MNmxsUl77OIKPKJcntJYtanoh
            W3Ofcw/1Vg0jDXJ+SzrrMpSoT8TB9ScNQMv0D2dhkliH8NUhRh5vPMvmVpoRs2Xp
            fGHr/yTV7iWOn3kBJd0rvnlpOz5R4ZReTcjZ3FOEZJlN4htR4Oli6o3MElnoM+UM
            kJ7KCs4aVd8Ev9bF7A/HkyP3SQMbdrqTDgmAwByB4Yokq926TKAVAtdoJ3BDClSz
            /a5kWJ5wZ0RyIf+Tb50C6pZRdAI1DjS7JkYvPNYYT8iHBzQsPw8WryZZ4CY4Z1us
            fxSdNJZb7I8kJ6A7iE9Whd1G+WqbTRRnQqox2To8OjvWj6zAKA3unZ1LErFLVgZ1
            kis4A4xvvK3+PWXG+cbVaWAJxieEVtNxy42hKkEu+hV8mNUtX8ah/ZFgXIEuPTeJ
            gkP59FBHiZTcyFk/ohNhDjZNdZNLAua49cQINeLPF86lBjNazZBA6g5WaY2wCzRk
            gWCefKxQ+BfTlRErQ0D1mtmVwEIVWWPpokfAnPtbfy56uLcoe5bvj4EX7UOCL8w0
            4QaQLyI+bGWEpyjC0DCaxq62i0m4z8i8oZhLrQoiSJWw2Db3mX0h4R26MScqRXws
            zcnEyPGn5pNHsAx7hJozAQSTNKHfrDBDoHNO1iPT7GaXqcuD0qTJ6hs0qx7KlFzS
            XAEENdW/rzmCkuP05443PfqjwP66KeAIF8fTf52XmIPHahDlWPFEB2faO48rztpO
            o8GjbgN0if42VEJv0FftTSi/iO0mpURPjbP+igV7L01Gg0bYfQsKEUxhJahX
            =/DdJ
            -----END PGP MESSAGE-----
          fp: 1A7742F3A542F0AF821B5728C63A01FBC1B86B44
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
