---
- hosts:
  - master
  - workers
  become: true
  gather_facts: true
  vars_prompt:
    name: "nuke_confirmation"
    prompt: "This will DESTROY the cluster. Do you wish to continue? [Y/n]"
    default: "n"
    private: no
  any_errors_fatal: yes
  pre_tasks:
  - name: check confirmation
    fail:
      msg: "Abort."
    when: nuke_confirmation != "Y"
  roles:
  - cluster-nuke
