---
name: renovate-helmrelease

on:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'

jobs:
  renovate-helmrelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Renovate Helm Releases
      uses: k8s-at-home/renovate-helm-releases@v1.4.2
      with:
        cluster-path: "./cluster"

    - name: Create pull request for renovatebot helm-release annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: renovate-helm-release-annotations
        delete-branch: true
        title: "Update renovatebot helm-release annotations"
        signoff: true
        committer: "Charlie Haley <charlie-haley@users.noreply.github.com>"
        author: "Charlie Haley <charlie-haley@users.noreply.github.com>"
        assignees: "charlie-haley"
        commit-message: "Update renovatebot helm-release annotations"
        body: |
          Add special annotations to HelmReleases inorder for Renovate to pick up new versions of Helm charts
        labels: renovate/helm-release-annotations
